import js from "@eslint/js";
import importX from "eslint-plugin-import-x";
import jsxA11y from "eslint-plugin-jsx-a11y";
import newline from "eslint-plugin-newline";
import perfectionist from "eslint-plugin-perfectionist";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import simpleImportSort from "eslint-plugin-simple-import-sort";
import globals from "globals";
import poupeTailwindcss from "@poupe/eslint-plugin-tailwindcss";
import tsParser from "@typescript-eslint/parser";
import betterTailwindcss from "eslint-plugin-better-tailwindcss";
import typeScriptSortKeysFix from "eslint-plugin-typescript-sort-keys";

export default [
    {
        ignores: [
            "node_modules/**",
            "dist/**",
            "build/**",
        ],
    },
    js.configs.recommended,
    {
        files: ["**/*.{js,jsx,ts,tsx}"],
        languageOptions: {
            ecmaVersion: 2020,
            globals: {
                ...globals.browser,
                ...globals.es2020,
                ...globals.node,
            },
            parserOptions: {
                ecmaFeatures: {
                    jsx: true,
                    modules: true,
                },
            },
            parser: tsParser,
            sourceType: "module",
        },
        plugins: {
            "import-x": importX,
            "jsx-a11y": jsxA11y,
            newline,
            perfectionist,
            react,
            "react-hooks": reactHooks,
            "simple-import-sort": simpleImportSort,
            "better-tailwindcss": betterTailwindcss,
            tailwindcss: poupeTailwindcss,
            "typescript-sort-keys": typeScriptSortKeysFix,
        },
        rules: {
            ...react.configs.recommended.rules,
            ...reactHooks.configs.recommended.rules,
            "array-callback-return": "off",
            "arrow-body-style": ["error", "as-needed"],
            "better-tailwindcss/enforce-shorthand-classes": "error",
            "better-tailwindcss/no-conflicting-classes": "error",
            "better-tailwindcss/no-duplicate-classes": "error",
            "better-tailwindcss/sort-classes": "error",
            "tailwindcss/prefer-theme-tokens": "error",
            camelcase: ["error", {
                ignoreDestructuring: true,
                ignoreGlobals: false,
                ignoreImports: true,
                properties: "always",
            }],
            "capitalized-comments": ["error"],
            "comma-dangle": ["error", "always-multiline"],
            complexity: ["error", 40],
            "consistent-return": "off",
            curly: ["error", "multi-or-nest"],
            "default-case": "off",
            "default-param-last": 0,
            "dot-location": ["error", "object"],
            "dot-notation": ["error", { allowKeywords: false }],
            eqeqeq: "error",
            "func-style": ["error", "declaration", { allowArrowFunctions: true }],
            "function-call-argument-newline": ["error", "always"],
            "import-x/no-cycle": 0,
            "import-x/no-named-as-default": 0,
            "import-x/no-named-as-default-member": 0,
            "import-x/no-unresolved": 0,
            "import-x/prefer-default-export": 0,
            indent: ["error", 4],
            "jsx-a11y/anchor-is-valid": "off",
            "jsx-a11y/click-events-have-key-events": "off",
            "jsx-a11y/html-has-lang": "off",
            "jsx-a11y/label-has-associated-control": "off",
            "jsx-a11y/media-has-caption": "off",
            "jsx-a11y/no-static-element-interactions": "off",
            "jsx-a11y/tabindex-no-positive": "off",
            "linebreak-style": "off",
            "max-depth": ["error", 4],
            "max-len": "off",
            "max-lines": ["error", {
                max: 900,
                skipBlankLines: true,
                skipComments: true,
            }],
            "max-lines-per-function": "off",
            "max-nested-callbacks": ["error", 10],
            "max-params": ["error", 18],
            "multiline-comment-style": ["error", "bare-block"],
            "newline/import-module": ["error", {
                minItems: 4,
                tab: 4,
            }],
            "newline/object-property": ["error", {
                minItems: 4,
                tab: 4,
            }],
            "no-alert": "error",
            "no-await-in-loop": "error",
            "no-cond-assign": "error",
            "no-else-return": "error",
            "no-eq-null": "error",
            "no-extra-semi": "error",
            "no-fallthrough": "error",
            "no-inline-comments": "error",
            "no-irregular-whitespace": "error",
            "no-lone-blocks": "error",
            "no-lonely-if": "error",
            "no-multi-spaces": "error",
            "no-nested-ternary": "off",
            "no-plusplus": "error",
            "no-redeclare": "error",
            "no-return-assign": "off",
            "no-self-compare": "error",
            "no-unexpected-multiline": "error",
            "no-unused-vars": "error",
            "no-use-before-define": "error",
            "no-useless-escape": "off",
            "no-var": "error",
            "object-curly-newline": ["error", {
                ExportDeclaration: {
                    consistent: true,
                    minProperties: 4,
                    multiline: true,
                },
                ImportDeclaration: {
                    consistent: true,
                    minProperties: 4,
                    multiline: true,
                },
                ObjectExpression: {
                    consistent: true,
                    minProperties: 4,
                    multiline: true,
                },
                ObjectPattern: {
                    consistent: true,
                    minProperties: 4,
                    multiline: true,
                },
            }],
            "object-property-newline": ["error", {
                allowAllPropertiesOnSameLine: false,
                allowMultiplePropertiesPerLine: false,
            }],
            "perfectionist/sort-objects": ["error", {
                ignoreCase: false,
                order: "asc",
                type: "natural",
            }],
            quotes: ["error", "double"],
            radix: 0,
            "react-hooks/set-state-in-effect": 0,
            "react-hooks/use-memo": 0,
            "react/button-has-type": 0,
            "react/display-name": "off",
            "react/forbid-prop-types": 0,
            "react/jsx-filename-extension": [1, { extensions: [".js", ".jsx", ".tsx"] }],
            "react/jsx-indent": ["error", 4],
            "react/jsx-indent-props": ["error", 4],
            "react/jsx-max-props-per-line": [1, { maximum: 1 }],
            "react/jsx-props-no-spreading": "off",
            "react/jsx-sort-props": [2, {
                callbacksLast: true,
                ignoreCase: false,
                locale: "auto",
                multiline: "last",
                noSortAlphabetically: false,
                shorthandFirst: false,
                shorthandLast: true,
            }],
            "react/no-danger": 0,
            "react/prop-types": 0,
            "react/react-in-jsx-scope": "off",
            "react/require-default-props": 0,
            "simple-import-sort/exports": "error",
            "simple-import-sort/imports": "error",
            "sort-keys": "off",
            "valid-typeof": "error",
            "vars-on-top": "error",
        },
        settings: {
            "import/extensions": [".js", ".jsx", ".tsx", ".ts"],
            "import/parsers": { "@typescript-eslint/parser": [".ts", ".tsx"] },
            "import/resolver": {
                node: {
                    extensions: [".js", ".jsx", ".tsx", ".ts"],
                    paths: ["src"],
                },
            },
            react: { version: "detect" },
        },
    },
];
