export const buttonsConstants = {
    addAdmin: "+ Add Admin",
    addRegion: "+ Add Region",
    addSuperAdmin: "+ Add Super Admin",
    back: "Back",
    backToHome: "Back to Home",
    backToLogin: "Back to login",
    close: "Close",
    forgotPasswordLink: "Reset it",
    goToLogin: "Go to Login",
    logout: "Log out",
    resetPassword: "Reset Password",
    sendResetLink: "Send Reset Link",
    signIn: "Sign In",
};
