export const labelsConstants = {
    confirmPassword: "Confirm Password",
    confirmPasswordPlaceholder: "Confirm your new password",
    email: "Email",
    emailExample: "admin@twindix.com",
    emailPlaceholder: "Enter your email",
    forgotPassword: "Forgot your password?",
    name: "Admin User",
    newPassword: "New Password",
    newPasswordPlaceholder: "Enter your new password",
    password: "Password",
    passwordPlaceholder: "Enter your password",
    sidebar: {
        accessControl: "Access Control",
        assessment: "Assessment",
        benchmarks: "Benchmarks",
        contact: "Contact",
        discounts: "Discounts",
        forgetPassword: "Forget Password",
        home: "Home",
        jobTitleQuestion: "Job Title Question",
        login: "Login",
        manageEnrollments: "Manage Enrollments",
        orders: "Orders",
        packages: "Packages",
        superAdmin: "Super Admin",
        templates: "Templates",
    },
};
