export const labelsConstants = {
    adminRole: "Administrator",
    admins: "Admins",
    adminUser: "Admin User",
    allRegions: "All Regions",
    closeSidebar: "Close sidebar",
    confirmPassword: "Confirm Password",
    confirmPasswordPlaceholder: "Confirm your new password",
    countries: "Countries",
    email: "Email",
    emailExample: "admin@twindix.com",
    emailPlaceholder: "Enter your email",
    emptyCell: "N/A",
    escapeKey: "Escape",
    forgotPassword: "Forgot your password?",
    name: "Name",
    newPassword: "New Password",
    newPasswordPlaceholder: "Enter your new password",
    noAdmins: "No admins assigned",
    noCountries: "No countries assigned",
    noRegions: "No regions found",
    noSuperAdmins: "No super admins found",
    noSuperAdminsAssigned: "No super admins assigned",
    password: "Password",
    passwordPlaceholder: "Enter your password",
    profile: "Profile",
    region: "Region",
    role: "Role",
    searchPlaceholder: "Search...",
    searchSuperAdminsPlaceholder: "Search by name or email...",
    settings: "Settings",
    sidebar: {
        accessControl: "Access Control",
        assessments: "Assessments",
        benchmarks: "Benchmarks",
        contact: "Contact",
        discounts: "Discounts",
        forgetPassword: "Forget Password",
        home: "Home",
        jobTitleQuestions: "Job Title Questions",
        login: "Login",
        manageEnrollments: "Manage Enrollments",
        orders: "Orders",
        packages: "Packages",
        permissions: "Permissions",
        regions: "Regions",
        superAdmins: "Super Admins",
        templates: "Templates",
        types: "Types",
    },
    superAdmins: "Super Admins",
    type: "Type",
};
