export const labelsConstants = {
    adminRole: "Administrator",
    confirmPassword: "Confirm Password",
    confirmPasswordPlaceholder: "Confirm your new password",
    email: "Email",
    emailExample: "admin@twindix.com",
    emailPlaceholder: "Enter your email",
    escapeKey: "Escape",
    forgotPassword: "Forgot your password?",
    name: "Admin User",
    newPassword: "New Password",
    newPasswordPlaceholder: "Enter your new password",
    password: "Password",
    passwordPlaceholder: "Enter your password",
    profile: "Profile",
    role: "Role",
    searchPlaceholder: "Search...",
    settings: "Settings",
    sidebar: {
        accessControl: "Access Control",
        assessments: "Assessments",
        benchmarks: "Benchmarks",
        contact: "Contact",
        discounts: "Discounts",
        forgetPassword: "Forget Password",
        home: "Home",
        jobTitleQuestions: "Job Title Questions",
        login: "Login",
        manageEnrollments: "Manage Enrollments",
        orders: "Orders",
        packages: "Packages",
        permissions: "Permissions",
        regions: "Regions",
        superAdmins: "Super Admins",
        templates: "Templates",
        types: "Types",
    },
};
