export const msgsConstants = {
    authProviderRequired: "useAuth must be used within an AuthProvider",
    checkInput: "Please check your input and try again.",
    emailRequired: "Email is required.",
    errorDescription: "An unexpected error occurred. Please try again or return to the homepage.",
    errorDetails: "Error details:",
    errorTitle: "Something Went Wrong",
    forgotPasswordSuccess: "A password reset link has been sent to your email. Please check your inbox.",
    genericError: "Something went wrong. Please try again.",
    invalidEmail: "Please enter a valid email address.",
    invalidResetLink: "This password reset link is invalid or has expired.",
    networkError: "Network Error",
    networkErrorDescription: "You appear to be offline. Please check your internet connection and try again.",
    networkErrorTitle: "No Internet Connection",
    notFoundDescription: "The page you are looking for does not exist or has been moved.",
    notFoundTitle: "Page Not Found",
    offlineBanner: "You are currently offline",
    onlineBanner: "Back online",
    passwordMinLength: "Password must be at least 8 characters.",
    passwordMismatch: "Passwords do not match.",
    passwordRequired: "Password is required.",
    resetPasswordSuccess: "Your password has been reset successfully.",
    themeProviderRequired: "useTheme must be used within a ThemeProvider",
};
